### PR TITLE
switch to a Markdown README

### PR DESCRIPTION
**Pull request by TheTechRobo**
If you're wondering, I used === instead of the hashtag system so you can
read it as plain text much easier

I also recommend you enable Issues in the settings - guthib disables it by default for forks.

### CODE REVIEW

**Comment by TheTechRobo** [comment]
do you want me to change to your commit name style?

**Comment by TheTechRobo** [comment]
ah screw it, im doing it anyway :)

**Comment by DacoTaco** [comment]
odd, i got not email/notification from this.

anyway. thanks!

ive been thinking of removing the fork thing, but this has been build on top of the code from mini and will most likely still have some code of mini in it by the end of it. i don't want to look like a thief and give credits where credits are due :/ 

ive enabled issues too. i didn't notice it wasn't there yet haha

**Comment by TheTechRobo** [comment]
Re why you didn't get an email: It appears you aren't "watching" the repo, so GitHub won't send you emails.

**Comment by DacoTaco** [comment]
i would have expected it to do that by default... *shrug*

**Pull request merged**
